CREATE TABLE LOGINS (
id SERIAL PRIMARY KEY,
NAMES text NOT NULL,
SURNAME text NOT NULL,
EMAIL text NOT NULL
);

CREATE TABLE EXPENCESE (
id SERIAL PRIMARY KEY,
CATEGORY text NOT NULL
);

CREATE TABLE TABLEREFF (
id SERIAL PRIMARY KEY,
DATE DATE not null,
EXPENCESENAME text not null,
AMOUNT INT NOT NULL,
NAMES_ID integer not null,
CATEGORY_ID integer not null,
FOREIGN KEY (NAMES_ID) REFERENCES LOGINS(id),
FOREIGN KEY (CATEGORY_ID) REFERENCES  EXPENCESE(id)
);


INSERT INTO EXPENCESE (CATEGORY) VALUES ('FOOD'),('TRANSPORT'),('ENTERTAINMENT'),('COMMUNICATION');

INSERT INTO LOGINS (NAMES, SURNAME, EMAIL)
VALUES ('siya', 'MPANI', 'C.YA@LIVE.COM');

-- expenses_id INT,
--  expenses_id expenses(ID)



